
Metrics/ClassLength:
  Max: 250

Style/ExplicitBlockArgument:
    Enabled: false

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
 Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 48

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 16
